wish: wish.o logger.o path_manager.o
	gcc -Wall -Werror -o wish wish.o logger.o path_manager.o

wish.o: wish.c
	gcc -c -Wall -Werror -o wish.o wish.c

logger.o: logger.c
	gcc -c -Wall -Werror -o logger.o logger.c

path_manager.o: path_manager.c
	gcc -c -Wall -Werror -o path_manager.o path_manager.c
